### ISSUE TITLE
ESDF Error Comparison

### ISSUE THREAD

**Issue by yinloonga** [VIS4ROB-lab/voxfield#2]
I use `cow_and_lady` to run `voxedt_server`, `voxblox_server` and `voxfield_server` respectively, and print the **Erroe-log** through the `VoxedtServer::evalEsdfRefOcc() function`.

> voxblox_server

```
No.147: 0.0599352 0.047562 370751
No.148: 0.0599352 0.047562 370751
No.149: 0.0599352 0.047562 370751
No.150: 0.0593335 0.0471059 374120
```

> voxfiele_server
```
No.77: 0.0425458 0.0297242 313890
No.78: 0.0429067 0.0301379 317133
No.79: 0.0441347 0.0307387 336464
No.80: 0.0445938 0.0309601 339265
```

> voxedt_server
```
No.37: 0.0173335 0.00275208 310175
No.38: 0.0120098 0.00155523 323364
No.39: 0.0118983 0.00152207 323668
No.40: 0.0118828 0.00151857 324090
```
The results are obvious. Compared with the results in the paper, the error of `voxfield_server` is indeed smaller than that of `voxblox_server`. However, the result of `voxedt_server` is actually smaller, and you mentioned that it is compared with the method based on the **occupancy grid** in `FIESTA`, so the code part should be fine. 
Because you refactored the EDT using `voxblox` data structure. So, can you help explain what's wrong here?
Thank you.

**Comment by YuePanEdward** [comment]
Thanks a lot for your interest in our work.
As mentioned https://github.com/VIS4ROB-lab/voxfield/issues/4, the ESDF error we reported in the paper is calculated by taking the ground truth 3D model as the reference. The `evalEsdfRefOcc()` function here is calculated based on the occupancy grid and does not need to load the ground truth 3D model for evaluation. The output of this function can be visualized on the fly but is not very reliable because the occupancy grid map it relied on also has some errors. In other words, It's only an indicator for debugging.
To reproduce the ESDF error reported in the paper, one needs to run the evaluation code provided [here](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/master/panoptic_mapping_utils/src/evaluation/map_evaluator.cpp) after mapping in which the ground truth model is loaded as the reference.

Metric definition in the paper:
> 
ESDF Error: For each voxel in the ESDF map, the
ground-truth signed distance is calculated as the Euclidean
distance from the voxel’s center to the nearest point in the
ground-truth point cloud. The voxel’s ESDF error is then
defined as the difference between the ground-truth value
and the mapped ESDF value, and the overall ESDF error is
computed as the average of all ESDF voxel errors. Compared
with the ESDF error metric in FIESTA [4], which is defined with
respect to the centers of the occupied voxels, the ESDF error
metric used here is not affected by the grid discretization and
is, therefore, more accurate.
>

**Comment by yinloonga** [comment]
Thank you very much for your timely reply. 
I also looked at the source code of [voxfield-panmap](https://github.com/VIS4ROB-lab/voxfield-panmap) yesterday. However, when I run the program with the `TSDF integrator type: single_raycast` and want to get the mapping result, the program shows the following error message. 
<img src=https://user-images.githubusercontent.com/72967324/216798969-8b283f4b-7978-40b9-8698-8545363afec4.png width=50% />

I first tried to debug this error, but I haven't found this bug yet. However, when I change the [TSDF integrator type](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/26b6ac4020a6087eadbb7ecbf67d2c4547918cf3/panoptic_mapping_ros/config/mapper/cow_mono.yaml#L67), such as changing to `class_raycast`, the program can run normally, but there is no result in Rviz. 
<img src=https://user-images.githubusercontent.com/72967324/216799060-3056e666-4d75-45ef-9828-b4a4311168d0.png width=50% />

And when I change the threshold of [visualization_interval](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/26b6ac4020a6087eadbb7ecbf67d2c4547918cf3/panoptic_mapping_ros/config/mapper/cow_mono.yaml#L14) into a positive value, e.g.+5, the program will appear other errors.
<img src=https://user-images.githubusercontent.com/72967324/216799079-2fb9b3d3-cbf8-44a7-bfda-2caed579a12c.png width=50% />  
Since the author is familiar with this framework, can you help me to try it? And I'm still debugging this bug.
Thank you again.

**Comment by yinloonga** [comment]
Hello, sorry to bother you again.
I used the `cow_and_lady` dataset and obtained the running results of `fiesta, edt, voxblox and voxfield` by adjusting the [cow_mono](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/26b6ac4020a6087eadbb7ecbf67d2c4547918cf3/panoptic_mapping_ros/config/mapper/cow_mono.yaml) parameters. Among them, the [tsdf_integrator:type](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/26b6ac4020a6087eadbb7ecbf67d2c4547918cf3/panoptic_mapping_ros/config/mapper/cow_mono.yaml#L67) of `fiesta, edt and voxblox` is `class_projective`, and that of `voxfield` is `single_raycast`. The parameters [esdf_integrator_name](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/26b6ac4020a6087eadbb7ecbf67d2c4547918cf3/panoptic_mapping_ros/config/mapper/cow_mono.yaml#L51) are their respective names.
By comparing the obtained `*.esdf` and `*.panmap` mapping results with `cow_and_lady_gt.ply`.
The result is as follows:
<details><summary>left:fiesta & right:edt</summary>
<p>
<img src="https://user-images.githubusercontent.com/72967324/216921590-865e76d8-9c68-4b0b-8bed-82d21378e2ca.png" width="800px"><img src="https://user-images.githubusercontent.com/72967324/216926085-397e1622-8406-4cde-a290-1558d2edbe5f.png" width="800px">
</p>  
</details>

<details><summary>left:voxblox  right:voxfield</summary>
<p>
<img src="https://user-images.githubusercontent.com/72967324/216922337-ddc360e6-c5d1-4d33-9861-a6d0223ee9ec.png" width="800px"><img src="https://user-images.githubusercontent.com/72967324/216922735-ee3f2655-6412-4366-9dca-b11d9c56b1ee.png" width="800px">
</p>
</details>

I don't know if the results I'm getting are correct or if **additional parameter settings** in [cow_mono](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/26b6ac4020a6087eadbb7ecbf67d2c4547918cf3/panoptic_mapping_ros/config/mapper/cow_mono.yaml) are required. Therefore, I hope you can give some suggestions after seeing it.
Thanks！
