### ISSUE TITLE
why limit the esdf error calculation?

### ISSUE THREAD

**Issue by maulanaazhari** [VIS4ROB-lab/voxfield#4]
in the code, you limit the esdf error calculation by 2*voxel_size, is there any reasons behind this calculation choice?
`cur_error_dist = std::min(
          error_trunc_limit,
          std::max(-error_trunc_limit, cur_error_dist));  // NOLINT`

**Comment by YuePanEdward** [comment]
Sorry for the late reply and thanks for your interest in our work.
This part of the code is only used for debugging and visualizing the error on-the-fly. The ESDF error here is calculated using the built occupancy grid as the reference (as the same metrics in FIESTA). 
The error we reported in the paper is calculated by taking the ground truth model as the reference. You may check the codes `MapEvaluator::computeEsdfError` from [here](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/master/panoptic_mapping_utils/src/evaluation/map_evaluator.cpp). But still, we follow [Voxblox](https://github.com/ethz-asl/voxblox/blob/c8066b04075d2fee509de295346b1c0b788c4f38/voxblox_ros/src/voxblox_eval.cc#L165) to use 2*voxel_size as the truncation distance for a fair comparison with baselines. This may reject some outliers caused by the incomplete ground truth model.
