### ISSUE TITLE
Question about the performance of mapping with the KITTI dataset

### ISSUE THREAD

**Issue by gogojjh** [VIS4ROB-lab/voxfield#5]
Thanks for your great work!

I have a question about running the code with the KITTI dataset (sequence 07, 2011_09_30_sync_0027). 
What is the specific voxel size of the map in Fig.6 and Fig.11 from your paper?
And I have tried the code ```roslaunch voxfield kitti_voxfield.launch``` with the same sequence (voxel size = 0.25, play bag speed: 0.25) and got the mesh map shown as the below figures.
It looks like that the constructed mesh map by me contains more *empty holes*. Could you please provide some hints in improving them?
Thanks!

![voxfield_07_mesh_map_1](https://user-images.githubusercontent.com/11897988/204292554-13c69b96-85bb-4117-b3ab-b8f00ccb6656.png)
![voxfield_07_mesh_map_3](https://user-images.githubusercontent.com/11897988/204292579-711ac0b5-de5b-4551-a940-03c3f6a94e5c.png)
![voxfield_07_mesh_map_2](https://user-images.githubusercontent.com/11897988/204292573-124d8d22-5343-429e-bec1-06b495b2a7ab.png)

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work and sorry for the late reply.
Those holes are caused by the outlier points in KITTI dataset (those ghost points under the ground). Those outliers would cause problems when calculating the normal and applying the projective correction.
After filtering those outliers (by rejecting the points whose z value is smaller than a threshold), we can achieve the following results (video with 10x speed) with the same parameter settings:
![voxfield_25cm_kitti_speed10x](https://user-images.githubusercontent.com/34207278/210832088-c8aad04d-d072-4d84-b883-2a1d655cf358.gif)

I will add the code for outlier filtering for KITTI later.

**Comment by gogojjh** [comment]
Hi.
Thanks for your reply! The results look great!
Also, could you please share the test bag of SemanticUSL? I found difficulty in downloading the data (may be the network issue)...

Thanks.

**Comment by YuePanEdward** [comment]
Here's the link to the rosbag for one sequence from SemanticUSL: [link](https://uni-bonn.sciebo.de/s/v6k4Asxj7JsrHG8). You may use the code from [voxfield-panmap](https://github.com/VIS4ROB-lab/voxfield-panmap) to test it.
There's only sequence 03,12,21,32 have ground truth labels.

**Comment by gogojjh** [comment]
thank you for your sharing!
